# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  go-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out code
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd ./goMod
          ls
          go run *.go
      # git 提交文件
      - name: Commit files
        run: |
          git config --local user.email "390353137@qq.com"
          git config --local user.name "noname"
          git add *
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'`" #动态提交信息
      # 推送到github仓库
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}



